name: 'Get & Cache Dependencies'
description: 'Get the dependencies (via npm) and cache them.'
runs:
  using: 'composite'
  steps:
    - name: ECHO STUFF
      shell: bash
      run: |
        echo "HELLO WORLD"
        ls -a /home
