name: 'Get & Cache Dependencies'
description: 'Get the dependencies (via npm) and cache them.'
runs:
  using: 'composite'
  steps:
    - name: ECHO STUFF
      run: |
        echo "HELLO WORLD"
        ls -a /

        # ls -a ${{ github.action_path }}


        # echo '${{ toJson(github) }}'

        # echo "_ACTIONS LS actions"
        # ls -a /__w/_actions/github-actions-course-davidfrankyu/custom-composite-gh-action/main

        # echo "_ACTIONS LS actions/cache/v3"
        # ls -a /__w/_actions/actions/cache/v3

        # echo "_ACTIONS LS checkout/v3/src"
        # ls -a /__w/_actions/actions/checkout/v3/src

        # echo "_ACTIONS LS v3/action.yml"
        # cat /__w/_actions/actions/checkout/v3/action.yml

        echo "GH ACTION PATH v3"
        echo "${{ github.action_path }}"
        pwd
        ls -a
      shell: bash
