name: 'Get & Cache Dependencies'
description: 'Get the dependencies (via npm) and cache them.'
runs:
  using: 'composite'
  steps:
    - name: ECHO STUFF
      run: |
        echo "HELLO WORLD"
        ls -a "__w"
        # ls -a ${{ github.action_path }}
        echo "${{ github.action_path }}"
        pwd
        ls -a
      shell: bash
